features:
  use_dns_addresses: false

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-6000000
  max_in_flight: 1
  max_errors: 1
variables: []

name: logs-platform

releases:
- {name: opensearch, version: latest}
- {name: routing, version: latest}
- {name: jammy-snort, version: latest}
- {name: bosh-dns-aliases, version: latest}
- {name: bpm, version: latest}
- {name: oauth2-proxy, version: latest}
- {name: secureproxy, version: latest}

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest


instance_groups:
#######################################################
#First deploy group - opensearch_data
# Data nodes are updated first as they are the most flexible with ingestors and need to be complete before managers.
# we run 2 at a time to cut down on collisions.
#######################################################
- name: opensearch_data
  instances: 5
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes: &consumes-opensearch-manager
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      opensearch:
        deployment_type:
        - platform
        oidc:
          enabled: true
          client_id: ((client_id))
          client_secret: ((client_secret))
          openid_connect_url: ((oidc_issuer_url))
          redirect_url: ((redirect_url))
          token_url: ((token_url))
        node:
          attributes:
            box_type: hot
          allow_cluster_manager: false
          allow_data: true
        limits:
          fd: 131072  # 2 ** 17
        health:
          timeout: 900
          disable_post_start: false
        recovery:
          delay_allocation_restart: "10m"
        config_options:
          indices.query.bool.max_clause_count: 2048
        jvm_options:
          - "-Dlog4j2.formatMsgNoLookups=true"
        cf:
          client_id: opensearch_client_id
  persistent_disk_type: logs_opensearch_os_platform_data
  stemcell: default
  azs: [z1,z2]
  vm_extensions:
  - logs-opensearch-profile
  vm_type: t3.large
  networks:
  - name: services
  update:
    max_in_flight: 2 
    serial: true # Block on this job to create deploy group 2
  env:
    bosh:
      swap_size: 0

#########################################################
#2nd deploy group - opensearch_manager
# manager is run after data nodes because old managers can talk to new data nodes but not vice versa.
# They are updated so one is always up as opensearch can survive on one manager in a disaster
#########################################################

- name: opensearch_manager
  instances: 3
  vm_extensions:
  - logs-opensearch-profile
  - 20GB_ephemeral_disk
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    consumes: *consumes-opensearch-manager
    provides:
      opensearch:
        as: opensearch_manager
    properties:
      opensearch:
        deployment_type:
        - platform
        oidc:
          enabled: true
          client_id: ((client_id))
          client_secret: ((client_secret))
          openid_connect_url: ((oidc_issuer_url))
          redirect_url: ((redirect_url))
          token_url: ((token_url))
        clustername: opensearch
        limits:
          fd: 131072 # 2 ** 17
        jvm_options:
          - "-Dlog4j2.formatMsgNoLookups=true"
        node:
          allow_cluster_manager: true
          allow_data: false
    release: opensearch
  - name: snort-config
    properties:
      snort:
        rules:
        - 'alert tcp any any -> any 9200 (msg:"Unexpected opensearch action"; content:"POST"; http_method; content: "logs-platform-app"; http_uri; content:"/_update"; http_uri; classtype:web-application-attack; sid:343080002; rev:1;)'
        - 'alert tcp any any -> any 9200 (msg:"Unexpected opensearch action"; content:"DELETE"; http_method; content: "logs-platform-app"; http_uri; classtype:web-application-attack; sid:343080004; rev:1;)'
    release: jammy-snort
  azs: [z1,z2]
  persistent_disk_type: logs_opensearch_os_master
  stemcell: default
  vm_type: t3.large
  networks:
   - name: services
  update:
    serial: true # Block on this job to create deploy group 2

#########################################################
#3rd deploy group - maintenance
# maintenance is ran after data and manager as it interacts with both.
#########################################################
- name: maintenance
  instances: 1
  vm_extensions:
    - 20GB_ephemeral_disk
    - logs-opensearch-ingestor-profile
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes: *consumes-opensearch-manager
    properties:
      opensearch:
        deployment_type:
        - platform
        oidc:
          client_id: ((client_id))
          client_secret: ((client_secret))
          openid_connect_url: ((oidc_issuer_url))
          redirect_url: ((redirect_url))
          token_url: ((token_url))
        clustername: opensearch
        limits:
          fd: 131072 # 2 ** 17
        jvm_options:
          - "-Dlog4j2.formatMsgNoLookups=true"
  - consumes:
      ingestor_link:
        from: ingestor_syslog
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    name: smoke_tests
    properties:
      smoke_tests:
        app_log:
          enabled: false
        index: logs-platform
        opensearch:
          ssl:
            ca: ((opensearch_node.ca))
            certificate: ((smoketest.certificate))
            private_key: ((smoketest.private_key))
        platform_log:
          enabled: true
        s3:
          environment: development
          region: ((region))
        tls:
          use_tls: true
          certificate: ((archiver_syslog_client_tls.certificate))
          private_key: ((archiver_syslog_client_tls.private_key))
    release: opensearch
  - name: upload_opensearch_config
    consumes: *consumes-opensearch-manager
    properties:
      opensearch_config:
        platform_alias: ((platform_alias))
        component_templates:
        - platform-shards-and-replica: /var/vcap/jobs/upload_opensearch_config/index-templates/shards-and-replicas-platform.json
        - index-settings: /var/vcap/jobs/upload_opensearch_config/index-templates/index-settings.json
        - index-mappings: /var/vcap/jobs/upload_opensearch_config/index-templates/index-mappings.json
        - component-index-mappings-base: /var/vcap/jobs/opensearch_templates/component-index-mappings-base.json
        - component-index-mappings-platform: /var/vcap/jobs/opensearch_templates/component-index-mappings-platform.json
        index_templates:
        - index-template: /var/vcap/jobs/opensearch_templates/index-template.json
        - index-template-platform: /var/vcap/jobs/opensearch_templates/index-template-platform.json
    release: opensearch
  - name: opensearch_templates
    consumes: *consumes-opensearch-manager
    properties:
      opensearch_config:
        platform_index_settings:
          index.mapping.total_fields.limit: 100
          index.queries.cache.enabled: "false"
        base_index_component_name: component-index-mappings-base
        index_mappings_component_name: index-mappings
        index_settings_component_name: index-settings
        platform_index_component_name: component-index-mappings-platform
        platform_shards_and_replicas_component_name: platform-shards-and-replica
    release: opensearch
  - name: upload-dashboards-objects
    release: opensearch
    consumes:
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      dashboards_objects:
        default_index: logs-platform-*
        upload_patterns:
        - {type: index-pattern, pattern: "/var/vcap/jobs/upload-dashboards-objects/dashboards-objects/index-pattern/logs-app*.json"}
        - {type: search, pattern: "/var/vcap/jobs/upload-dashboards-objects/dashboards-objects/search/app-*.json"}
        - {type: visualization, pattern: "/var/vcap/jobs/upload-dashboards-objects/dashboards-objects/visualization/App-*.json"}
        - {type: dashboard, pattern: "/var/vcap/jobs/upload-dashboards-objects/dashboards-objects/dashboard/App-*.json"}
      opensearch_dashboards:
        host: opensearch_dashboards.opensearch.internal
  stemcell: default
  azs: [z1,z2]
  vm_type: t3.large
  networks:
  - name: services
  update:
    serial: true # Block on this job to create deploy group 3

#########################################################
#5th deploy group ingestors
# Ingestors are run second to last and updated one at a time to avoid collisions
#########################################################
- name: ingestor
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes: *consumes-opensearch-manager
    properties:
      opensearch:
        deployment_type:
        - platform
        heap_size: 1G
        http_host: 127.0.0.1
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
        oidc:
          enabled: true
          client_id: ((client_id))
          client_secret: ((client_secret))
          openid_connect_url: ((oidc_issuer_url))
          redirect_url: ((redirect_url))
          token_url: ((token_url))
  - name: ingestor_syslog
    consumes: *consumes-opensearch-manager
    properties:
      logstash:
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
        queue:
          max_bytes: 30gb
      logstash_parser:
        opensearch:
          data_hosts:
          - localhost
          index: ((platform_alias))
          index_type: '%{@type}'
          ssl:
            ca: ((opensearch_node.ca))
            certificate: ((logstash.certificate))
            private_key: ((logstash.private_key))
        filters:
          - logs-for-cf: /var/vcap/packages/cf-logstash-filters/logstash-platform-default.conf
        outputs:
        - plugin: s3
          options:
            region: ((region))
            bucket: ((bucket))
            server_side_encryption: true
            prefix: "%{+yyyy/MM/dd/HH/mm}"
            encoding: "gzip"
            temporary_directory: /var/vcap/data/ingestor_syslog/s3_temp
            # note that this is different than in the archivers
            # here, we're uploading the parsed message as json, not the raw log line
            codec: json_lines
        - plugin: opensearch
          options: {}
        deployment_dictionary:
        - /var/vcap/packages/base-logstash-filters/deployment_lookup.yml
        - /var/vcap/jobs/deployment_lookup_config/config/deployment_lookup.yml
      logstash_ingestor:
        type: platform
        syslog:
          port: 5431
        syslog_tls:
          port: 6972
          ssl_cert: ((ingestor_syslog_server_tls.certificate))
          ssl_key: ((ingestor_syslog_server_tls.private_key))
    provides:
      ingestor:
        as: ingestor_link
    release: opensearch
  - name: deployment_lookup_config
    release: opensearch
  vm_type: t3.medium
  vm_extensions:
  - platform-opensearch-ingestor-profile
  - platform-syslog-lb
  - 20GB_ephemeral_disk
  persistent_disk_type: logs_opensearch_ingestor
  stemcell: default
  azs: [z1,z2]
  networks:
  - name: services
  update:
    max_in_flight: 2 
    serial: true # Block on this job to create deploy group 5

- name: ingestor_s3
  instances: 0
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes: *consumes-opensearch-manager
    properties:
      opensearch:
        deployment_type:
        - platform
        heap_size: 1G
        http_host: 127.0.0.1
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
  - consumes: *consumes-opensearch-manager
    name: ingestor_s3
    properties:
      logstash:
        type: new
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
        queue:
          max_bytes: 30gb
      logstash_ingestor:
        s3:
          bucket: ((recovery_bucket))
          region: ((region))
          prefix: 2026/03/25/05/
        syslog_tls:
          port: 6972
          ssl_cert: ((ingestor_syslog_server_tls.certificate))
          ssl_key: ((ingestor_syslog_server_tls.private_key))
      logstash_parser:
        opensearch:
          data_hosts:
          - localhost
          index: "jason"
          index_type: '%{@type}'
          ssl:
            ca: ((opensearch_node.ca))
            certificate: ((logstash.certificate))
            private_key: ((logstash.private_key))
    provides:
      ingestor:
        as: ingestor_s3
    release: opensearch
  - name: deployment_lookup_config
    release: opensearch
  azs: [z1,z2]
  networks:
  - name: services
  persistent_disk_type: logs_opensearch_ingestor
  stemcell: default
  vm_extensions:
  - platform-opensearch-ingestor-profile
  - 20GB_ephemeral_disk
  vm_type: t3.large
  update:
    serial: true # Block on this job to create deploy group 6

#########################################################
# 9th deploy group - dashboards
# Dashboard is ran last as it checks the types of other instances when restarting. all dashboard nodes must either be updated at the same
# time or have instances not ran yet turned off for opensearch.
# IF DASHBOARD IS UPDATING WITH A OLD VERSION BOTH WILL ERROR
#########################################################
- name: opensearch_dashboards
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes: *consumes-opensearch-manager
    properties:
      opensearch:
        deployment_type:
        - platform
        oidc:
          client_id: ((client_id))
          client_secret: ((client_secret))
          openid_connect_url: ((oidc_issuer_url))
          redirect_url: ((redirect_url))
          token_url: ((token_url))
        heap_size: 1G
        http_host: 127.0.0.1
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
  - name: opensearch_dashboards
    consumes: *consumes-opensearch-manager
    properties:
      opensearch_dashboards:
        oidc:
          enabled: true
          redirect: "logs-platform-test.dev.us-gov-west-1.aws-us-gov.cloud.gov"
        config_options:
          server.maxPayloadBytes: 4194304
        console.enabled: false
        server:
          ssl:
            enabled: false
        port: 5605
        defaultAppId: dashboard/platform-overview-dashboard
        env:
        - NODE_ENV: production
        health:
          timeout: 600
          disable_post_start: true
        index: ((dashboard_index))
        memory_limit: 75
        multitenancy:
          enabled: false
    release: opensearch
  vm_extensions:
  - 15GB_ephemeral_disk
  - logs-opensearch-profile
  - platform-opensearch-lb
  stemcell: default
  azs: [z1]
  networks:
   - name: services
  env:
    bosh:
      swap_size: 0
  update:
    canaries: 100%
    max_in_flight: 100%
    serial: true
